/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.main;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
/**
 *
 * @author DUC
 */
public class addSP extends javax.swing.JFrame {
    private String newlink;
    private String ManaName;
    /**
     * Creates new form addSP
     */
    public addSP(String nama) {
        this.ManaName=nama;
        initComponents();
        
        incolor.addItemListener(new ItemListener() {
                    @Override
                    public void itemStateChanged(ItemEvent e) {
                        vcolor.setBackground(setColor(incolor.getSelectedItem().toString()));
                    }
                });
    }
    Color setColor(String a){
        a.replaceAll("  ", "");
        if(a.contains("Black")){
            return Color.BLACK;
        }else if(a.contains("Blue")){
            return Color.BLUE;
        }else if(a.contains("Pink")){
            return Color.PINK;
        }else if(a.contains("White")){
            return Color.WHITE;
        }else if(a.contains("Red")){
            return Color.RED;
        }else if(a.contains("Orange")){
            return Color.ORANGE;
        }else{
            return Color.GRAY;
        }
    }
    private void scaleImage(String location, JLabel label){
        ImageIcon icon = new ImageIcon(location);
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        label.setIcon(scaledIcon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel15 = new javax.swing.JPanel();
        inname = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        incpu = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        inram = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        inssd = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        invga = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        indisplay = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        vcolor = new javax.swing.JPanel();
        incolor = new javax.swing.JComboBox<>();
        jPanel22 = new javax.swing.JPanel();
        inprice = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        inpriceS = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        inid = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        vimg = new javax.swing.JLabel();
        inimg = new javax.swing.JButton();
        bottom = new javax.swing.JPanel();
        CANCEL = new javax.swing.JButton();
        DONE = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 102));
        jLabel25.setText("THÊM SẢN PHẨM");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 240, 60));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 970, 10));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inname.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jPanel15.add(inname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 180, 40));

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 200, 80));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        incpu.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jPanel17.add(incpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 140, 40));

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 160, 80));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inram.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jPanel20.add(inram, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 120, 40));

        jPanel1.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 140, 80));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inssd.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jPanel18.add(inssd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 150, 40));

        jPanel1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 170, 80));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        invga.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jPanel21.add(invga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 150, 40));

        jPanel1.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 170, 80));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indisplay.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jPanel16.add(indisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 22, 170, 40));

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 210, 80));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vcolor.setBackground(new java.awt.Color(0, 0, 0));
        vcolor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout vcolorLayout = new javax.swing.GroupLayout(vcolor);
        vcolor.setLayout(vcolorLayout);
        vcolorLayout.setHorizontalGroup(
            vcolorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        vcolorLayout.setVerticalGroup(
            vcolorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        jPanel10.add(vcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, 40));

        incolor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black", "Gray", "White", "Blue", "Pink", "Red", "Orange" }));
        incolor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incolorMouseClicked(evt);
            }
        });
        jPanel10.add(incolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 30));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 110, 100));

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inprice.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jPanel22.add(inprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 100, 40));

        jPanel1.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 120, 80));

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inpriceS.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jPanel23.add(inpriceS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 40));

        jPanel1.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 110, 80));

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel24.add(inid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 30));

        jPanel1.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 80, 50));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vimg.setText("         none");
        vimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(vimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 70));

        inimg.setBackground(new java.awt.Color(255, 204, 153));
        inimg.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        inimg.setText("Chose");
        inimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inimgActionPerformed(evt);
            }
        });
        jPanel19.add(inimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, 30));

        jPanel1.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, 120, 130));

        bottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CANCEL.setBackground(new java.awt.Color(255, 0, 0));
        CANCEL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CANCEL.setForeground(new java.awt.Color(255, 255, 255));
        CANCEL.setText("Hủy");
        CANCEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CANCELMouseClicked(evt);
            }
        });
        bottom.add(CANCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 80, 40));

        DONE.setBackground(new java.awt.Color(0, 204, 0));
        DONE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DONE.setForeground(new java.awt.Color(255, 255, 255));
        DONE.setText("Hoàn tất");
        DONE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DONEMouseClicked(evt);
            }
        });
        bottom.add(DONE, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 110, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setText("Kiểm tra kỹ thông tin trước khi hoàn tất !!");
        bottom.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 310, 40));

        jPanel1.add(bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, 430, 1260, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Tên sản phẩm");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 140, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("CPU");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 100, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("RAM");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 100, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("SSD");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 100, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("VGA");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 100, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("DISPLAY");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 100, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("COLOR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 100, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("PRICE");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 90, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("PRICE*");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 100, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("ID");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 60, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("PICTURE");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 240, 90, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void incolorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incolorMouseClicked

    }//GEN-LAST:event_incolorMouseClicked

    private void inimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inimgActionPerformed
        JFileChooser f=new JFileChooser("C:\\Users\\DUC\\Documents\\JAVA\\BanLapTop\\src\\com.icon");
        f.setDialogTitle("Chọn ảnh");
        f.showOpenDialog(null);
        File nf=f.getSelectedFile();
        newlink=nf.getAbsolutePath();
        if(newlink!=null){
            scaleImage(nf.getAbsolutePath(), vimg);
        }else{
        }
    }//GEN-LAST:event_inimgActionPerformed

    private void CANCELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANCELMouseClicked
        try {
            new Manager(ManaName).setVisible(true);     dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_CANCELMouseClicked

    private void DONEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DONEMouseClicked
        if(true){
            try {
                Connection conn=db.DBconnect.getConnection();
                String sql="select *from laptop";
                PreparedStatement ps=conn.prepareCall(sql);
                ResultSet rs=ps.executeQuery();
                sql = "INSERT INTO laptop " +
                    "VALUES ('"+inname.getText()+"', '"+incpu.getText()+"', '"+inram.getText()+"', '"
                    +inssd.getText()+"', '"+invga.getText()+"','"+indisplay.getText()+"','"+incolor.getSelectedItem().toString()
                    +"',"+inprice.getText()+","+inid.getText()+",'"+inpriceS.getText()+"','"+newlink+"')";
                    ps=conn.prepareCall(sql);
                    ps.execute();
                new Manager(ManaName).setVisible(true) ;    dispose();
            } catch (Exception e) {
            }
        }        
    }//GEN-LAST:event_DONEMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addSP("cc").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CANCEL;
    private javax.swing.JButton DONE;
    private javax.swing.JPanel bottom;
    private javax.swing.JComboBox<String> incolor;
    private javax.swing.JTextField incpu;
    private javax.swing.JTextField indisplay;
    private javax.swing.JTextField inid;
    private javax.swing.JButton inimg;
    private javax.swing.JTextField inname;
    private javax.swing.JTextField inprice;
    private javax.swing.JTextField inpriceS;
    private javax.swing.JTextField inram;
    private javax.swing.JTextField inssd;
    private javax.swing.JTextField invga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel vcolor;
    private javax.swing.JLabel vimg;
    // End of variables declaration//GEN-END:variables
}
