/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.main;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author DUC
 */
public class bill extends javax.swing.JFrame {
    private String name;
    private float Voucher;
    private String idVoucher="nullvou";
    private int TIEN;
    /**
     * Creates new form bill
     */
    public bill(String name, float voucher) throws ClassNotFoundException, SQLException {
        this.name=name;
        this.Voucher=voucher;        
        initComponents();        
        databill();
        this.voucher.setText(this.Voucher+"");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }
    void setIdvou(String a){
        this.idVoucher=a;
    }
    public void databill() throws ClassNotFoundException, SQLException{
        Connection conn=db.DBconnect.getConnection();
        String sql="select *from laptop";
        PreparedStatement ps=conn.prepareCall(sql);
        ResultSet rs=ps.executeQuery();
        while(rs.next()){
            if(rs.getString(1).contains(name)){
                int price=rs.getInt(8);
                DG.setText(rs.getString("PriceS"));
                NAME.setText(name);
                sql="select *from giohang";
                ps=conn.prepareCall(sql);
                rs=ps.executeQuery();
                while(rs.next()){
                    if(rs.getString(1).contains(name)){
                        SL.setText(rs.getInt(4)+"");
                        price*=rs.getInt(4);
                        TGia.setText((price)+"");
                        break;
                    }
                }
                TIEN=(int)(price-price*(Voucher/100));
                TONGTIEN.setText(TIEN+"");
                break;
            }
        }
        
    }
    public String getName(){
        return this.name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ttsp = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        NAME = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        DG = new javax.swing.JLabel();
        ttsp1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        SL = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        TGia = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        voucher = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TONGTIEN = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        inpvou = new javax.swing.JTextField();
        checkvou = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        insdt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        indiachi = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        innote = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        huy = new javax.swing.JButton();
        xacnhan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thanh Toán");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ttsp.setBackground(new java.awt.Color(255, 255, 255));
        ttsp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ttsp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 153));
        jLabel4.setText("HÓA ĐƠN SẢN PHẨM");
        ttsp.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 270, 60));

        jSeparator2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ttsp.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 420, 10));

        NAME.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NAME.setForeground(new java.awt.Color(255, 0, 0));
        NAME.setText("Gaming Asus TUF Core i7 12700H          ");
        ttsp.add(NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 350, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("VNĐ");
        ttsp.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 50, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Đơn giá :");
        ttsp.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 30));

        DG.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        DG.setForeground(new java.awt.Color(255, 0, 51));
        DG.setText("56.000.000");
        ttsp.add(DG, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 110, 30));

        ttsp1.setBackground(new java.awt.Color(255, 255, 255));
        ttsp1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ttsp1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 153));
        jLabel14.setText("HÓA ĐƠN SẢN PHẨM");
        ttsp1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 270, 60));

        jSeparator3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ttsp1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 420, 10));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Tên SP : ");
        ttsp1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("Gaming Asus TUF Core i7 12700H          ");
        ttsp1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 350, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 51));
        jLabel17.setText("VNĐ");
        ttsp1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 50, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setText("Đơn giá :");
        ttsp1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 51));
        jLabel19.setText("56.000.000");
        ttsp1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 110, 30));

        ttsp.add(ttsp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 420, 450));

        SL.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        SL.setForeground(new java.awt.Color(255, 0, 51));
        SL.setText("1");
        ttsp.add(SL, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 110, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setText("Số lượng :");
        ttsp.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 30));
        ttsp.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 420, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Tên SP : ");
        ttsp.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, 40));

        TGia.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        TGia.setForeground(new java.awt.Color(255, 0, 51));
        TGia.setText("56.000.000");
        ttsp.add(TGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 110, 50));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 51));
        jLabel24.setText("VNĐ");
        ttsp.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 50, 50));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Nhập voucher :");
        ttsp.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 50));

        voucher.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        voucher.setForeground(new java.awt.Color(255, 0, 51));
        voucher.setText("56");
        ttsp.add(voucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 60, 40));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 51));
        jLabel27.setText("-");
        ttsp.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 40, 40));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 51));
        jLabel28.setText("%");
        ttsp.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 30, 40));
        ttsp.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 420, 10));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setText(" Voucher :");
        ttsp.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 90, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 204), java.awt.Color.yellow, null, null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Phải trả :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 50));

        TONGTIEN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TONGTIEN.setForeground(new java.awt.Color(255, 0, 51));
        TONGTIEN.setText("56.000.000");
        jPanel2.add(TONGTIEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 120, 50));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 51));
        jLabel31.setText("VNĐ");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 60, 50));

        ttsp.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 310, 50));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel32.setText("Thắc mắc? Liên hệ : 0359100154 (Anh Duck)");
        ttsp.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 280, 20));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("Tổng : ");
        ttsp.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 80, 50));
        ttsp.add(inpvou, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 200, 30));

        checkvou.setBackground(new java.awt.Color(204, 255, 204));
        checkvou.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkvou.setForeground(new java.awt.Color(0, 51, 51));
        checkvou.setText("Check");
        checkvou.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkvouMouseClicked(evt);
            }
        });
        ttsp.add(checkvou, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 70, 30));

        jPanel1.add(ttsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 430, 450));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 153));
        jLabel3.setText("THÔNG TIN KHÁCH HÀNG");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 270, 60));

        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 420, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Ghi chú :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 90, 40));

        insdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        insdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insdtActionPerformed(evt);
            }
        });
        insdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                insdtKeyTyped(evt);
            }
        });
        jPanel3.add(insdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 220, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Tên :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 50, 40));

        inname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                innameActionPerformed(evt);
            }
        });
        jPanel3.add(inname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 290, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Số điện thoại :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 140, 40));

        indiachi.setColumns(20);
        indiachi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        indiachi.setRows(5);
        jScrollPane1.setViewportView(indiachi);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 360, 130));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Địa chỉ :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 100, 40));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        innote.setColumns(20);
        innote.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        innote.setRows(5);
        jScrollPane2.setViewportView(innote);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 270, 80));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 450));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        huy.setBackground(new java.awt.Color(255, 51, 51));
        huy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        huy.setForeground(new java.awt.Color(255, 255, 255));
        huy.setText("Hủy");
        huy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                huyMouseClicked(evt);
            }
        });
        huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huyActionPerformed(evt);
            }
        });
        jPanel4.add(huy, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 7, 97, 46));

        xacnhan.setBackground(new java.awt.Color(0, 204, 51));
        xacnhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        xacnhan.setForeground(new java.awt.Color(255, 255, 255));
        xacnhan.setText("Xác nhận");
        xacnhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xacnhanMouseClicked(evt);
            }
        });
        xacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xacnhanActionPerformed(evt);
            }
        });
        jPanel4.add(xacnhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 7, 117, 46));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DUCK STORE");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 160, 40));

        jLabel2.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setText("Chan thanh cam on Quy Khach !");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 310, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 860, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_huyActionPerformed

    private void xacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xacnhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xacnhanActionPerformed

    private void insdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insdtActionPerformed

    private void innameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_innameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_innameActionPerformed

    private void insdtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_insdtKeyTyped
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_insdtKeyTyped

    private void huyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_huyMouseClicked
        Home a=new Home();
        a.setVisible(true);
        a.gettab().setSelectedIndex(2);
        dispose();
    }//GEN-LAST:event_huyMouseClicked

    private void xacnhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xacnhanMouseClicked
        if(indiachi.getText().isEmpty()||inname.getText().equals("")||insdt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nhập thiếu thông tin !");            
        }else{
            try {
                Connection conn=db.DBconnect.getConnection();
                String sql="select *from giohang";
                PreparedStatement ps=conn.prepareCall(sql);
                ResultSet rs=ps.executeQuery();
                sql="delete from giohang where Name='"+name+"';";
                ps=conn.prepareCall(sql);
                ps.execute();
                sql = "INSERT INTO khachhang " +
                        "VALUES ('"+inname.getText()+"', '"+insdt.getText()+"', '"+indiachi.getText()+"', '"
                                +innote.getText()+"', '"+this.name+"','"+SL.getText()+"', "+voucher.getText()+","+TIEN+")";
                ps=conn.prepareCall(sql);
                ps.execute();
                if(idVoucher=="nullvou"){
                    
                }else{

                    sql="select *from voucher";
                    ps=conn.prepareCall(sql);
                    rs=ps.executeQuery();
                    
                    while(rs.next()){
                        if(rs.getString(1).contains(idVoucher)){
                            int giam=0, sl=0, id=0;
                            giam=rs.getInt(2);
                            sl=rs.getInt(3)-1;
                            id=rs.getInt(4);  
                            sql="delete from voucher where ma='"+idVoucher+"';";
                            ps=conn.prepareCall(sql);
                            ps.execute();
                            sql = "INSERT INTO voucher " +
                                "VALUES ('"+idVoucher+"', "+giam+", "+sl+", "+id+")";
                            ps=conn.prepareCall(sql);
                            ps.execute();
                            break;
                        }
                    }
                }
            } catch (Exception e) {
            }
            JOptionPane.showMessageDialog(null, "Đã đặt hàng !");
            Home a=new Home();
            a.setVisible(true);
            a.gettab().setSelectedIndex(2);
            dispose();
        }        
    }//GEN-LAST:event_xacnhanMouseClicked

    private void checkvouMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkvouMouseClicked
        try {
            Connection conn=db.DBconnect.getConnection();
            String sql="select *from voucher";
            PreparedStatement ps=conn.prepareCall(sql);
            ResultSet rs=ps.executeQuery();
            int tmp=1;
            while(rs.next()){                
                if(rs.getString(1).contains(inpvou.getText())&&rs.getInt(3)!=0  ){
                    this.idVoucher=rs.getString(1);
                    bill Bill=new bill(name, rs.getInt(2));
                    Bill.setIdvou(idVoucher);
                    Bill.setVisible(true);
                    dispose();
                    tmp=0;
                    break;
                }
            }
            if(tmp==1){
                JOptionPane.showMessageDialog(null, "Voucher không hợp lệ !!");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_checkvouMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new bill("a", 0).setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DG;
    private javax.swing.JLabel NAME;
    private javax.swing.JLabel SL;
    private javax.swing.JLabel TGia;
    private javax.swing.JLabel TONGTIEN;
    private javax.swing.JButton checkvou;
    private javax.swing.JButton huy;
    private javax.swing.JTextArea indiachi;
    private javax.swing.JTextField inname;
    private javax.swing.JTextArea innote;
    private javax.swing.JTextField inpvou;
    private javax.swing.JTextField insdt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel ttsp;
    private javax.swing.JPanel ttsp1;
    private javax.swing.JLabel voucher;
    private javax.swing.JButton xacnhan;
    // End of variables declaration//GEN-END:variables
}
