/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.main;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;

/**
 *
 * @author DUC
 */
public class editSP extends javax.swing.JFrame {
    private String ManaName;
    private String idName;
    private String newlink;
    private String oldlink;    
    /**
     * Creates new form editSP
     */
    public editSP(String name, String ManaName) throws ClassNotFoundException, SQLException {
        this.idName=name.replaceAll("   ", "");
        this.ManaName=ManaName;
        initComponents();
        Connection conn=db.DBconnect.getConnection();
        String sql="select *from laptop";
        PreparedStatement ps=conn.prepareCall(sql);
        ResultSet rs=ps.executeQuery();
        while(rs.next()){
            if(rs.getString(1).contains(this.idName)){
                tensp.setText(rs.getString(1).replaceAll("  ", ""));
                cpu.setText(rs.getString(2).replaceAll("  ", ""));
                ram.setText(rs.getString(3).replaceAll("  ", ""));
                ssd.setText(rs.getString(4).replaceAll("  ", ""));
                vga.setText(rs.getString(5).replaceAll("  ", ""));
                display.setText(rs.getString(6).replaceAll("  ", ""));
                color.setBackground(setColor((rs.getString(7))));
                price.setText(rs.getString(8).replaceAll("  ", ""));
                priceS.setText(rs.getString(10).replaceAll("  ", ""));
                id.setText(rs.getString(9).replaceAll("  ", ""));
                scaleImage(rs.getString(11).replaceAll("  ", ""), img);
                
                newlink=rs.getString(11).replaceAll("  ", "");
                oldlink=rs.getString(11).replaceAll("  ", "");
                
                inname.setText(rs.getString(1).replaceAll("  ", ""));
                incpu.setText(rs.getString(2).replaceAll("  ", ""));
                inram.setText(rs.getString(3).replaceAll("  ", ""));
                inssd.setText(rs.getString(4).replaceAll("  ", ""));
                invga.setText(rs.getString(5).replaceAll("  ", ""));
                indisplay.setText(rs.getString(6).replaceAll("  ", ""));
                vcolor.setBackground(setColor((rs.getString(7))));
                inprice.setText(rs.getString(8).replaceAll("  ", ""));
                inpriceS.setText(rs.getString(10).replaceAll("  ", ""));
                inid.setText(rs.getString(9).replaceAll("  ", ""));
                scaleImage(rs.getString(11).replaceAll("  ", ""), vimg);
                
                incolor.setSelectedItem(rs.getString(7).replaceAll(" ", ""));
                incolor.addItemListener(new ItemListener() {
                    @Override
                    public void itemStateChanged(ItemEvent e) {
                        vcolor.setBackground(setColor(incolor.getSelectedItem().toString()));
                    }
                });
            }
        }
    }
    private void scaleImage(String location, JLabel label){
        ImageIcon icon = new ImageIcon(location);
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        label.setIcon(scaledIcon);
    }
    Color setColor(String a){
        a.replaceAll("  ", "");
        if(a.contains("Black")){
            return Color.BLACK;
        }else if(a.contains("Blue")){
            return Color.BLUE;
        }else if(a.contains("Pink")){
            return Color.PINK;
        }else if(a.contains("White")){
            return Color.WHITE;
        }else if(a.contains("Red")){
            return Color.RED;
        }else if(a.contains("Orange")){
            return Color.ORANGE;
        }else{
            return Color.GRAY;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        bottom = new javax.swing.JPanel();
        CANCEL = new javax.swing.JButton();
        DONE = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        color = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tensp = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        display = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cpu = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ssd = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        ram = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        vga = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        priceS = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        vcolor = new javax.swing.JPanel();
        incolor = new javax.swing.JComboBox<>();
        jPanel15 = new javax.swing.JPanel();
        inname = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        indisplay = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        incpu = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        inssd = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        vimg = new javax.swing.JLabel();
        inimg = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        inram = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        invga = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        inprice = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        inpriceS = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        inid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1490, 10));

        bottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CANCEL.setBackground(new java.awt.Color(255, 0, 0));
        CANCEL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CANCEL.setForeground(new java.awt.Color(255, 255, 255));
        CANCEL.setText("Hủy");
        CANCEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CANCELMouseClicked(evt);
            }
        });
        bottom.add(CANCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 80, 30));

        DONE.setBackground(new java.awt.Color(0, 204, 0));
        DONE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DONE.setForeground(new java.awt.Color(255, 255, 255));
        DONE.setText("Hoàn tất");
        DONE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DONEMouseClicked(evt);
            }
        });
        bottom.add(DONE, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 110, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setText("Kiểm tra kỹ thông tin trước khi hoàn tất !!");
        bottom.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 460, 30));

        jPanel1.add(bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1490, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("COLOR");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 20));

        color.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout colorLayout = new javax.swing.GroupLayout(color);
        color.setLayout(colorLayout);
        colorLayout.setHorizontalGroup(
            colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        colorLayout.setVerticalGroup(
            colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel3.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, 90, 80));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Tên sản phẩm");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, 20));

        tensp.setText("Gaming Asus TUF Core i7 12700H          ");
        jPanel4.add(tensp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 220, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 80));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("DISPLAY");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 70, 20));

        display.setText("15.6 inch, 2560 x 1440 , IPS, 165 Hz    ");
        jPanel5.add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, 190, 80));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("CPU");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 60, 20));

        cpu.setText("AMD Ryzen 7 PRO - 6850U                 ");
        jPanel6.add(cpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 160, 80));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("SSD");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 60, 20));

        ssd.setText("SSD 256 GB PCIe NVMe M.2                ");
        jPanel7.add(ssd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 170, 80));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("PICTURE");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        img.setText("     none");
        img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 40));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 50, 80, 80));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("RAM");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, 20));

        ram.setText("32GB DDR4-3200MHz                       ");
        jPanel9.add(ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 30));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 140, 80));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("VGA");
        jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 60, 20));

        vga.setText("SSD 256 GB PCIe NVMe M.2                ");
        jPanel11.add(vga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 30));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 170, 80));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("PRICE");
        jPanel12.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, 20));

        jLabel20.setText("VNĐ");
        jPanel12.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 40, 30));

        price.setText("65000000");
        jPanel12.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 30));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 50, -1, 80));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("PRICE*");
        jPanel13.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 20));

        priceS.setText("65.000.000");
        jPanel13.add(priceS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, 30));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 50, 90, 80));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("ID");
        jPanel14.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 20));

        id.setText("10");
        jPanel14.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 30, 30));

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 50, 50, 80));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 102));
        jLabel25.setText("THÔNG TIN MỚI");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 420, 30));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 102));
        jLabel26.setText("THÔNG TIN CŨ");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 420, 30));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vcolor.setBackground(new java.awt.Color(0, 0, 0));
        vcolor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout vcolorLayout = new javax.swing.GroupLayout(vcolor);
        vcolor.setLayout(vcolorLayout);
        vcolorLayout.setHorizontalGroup(
            vcolorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        vcolorLayout.setVerticalGroup(
            vcolorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel10.add(vcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, -1));

        incolor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black", "Gray", "White", "Blue", "Pink", "Red", "Orange" }));
        incolor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incolorMouseClicked(evt);
            }
        });
        jPanel10.add(incolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 180, 90, 80));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inname.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        inname.setText("Gaming Asus TUF Core i7 12700H          ");
        jPanel15.add(inname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 180, 40));

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 200, 80));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indisplay.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        indisplay.setText("Gaming Asus TUF Core i7 12700H          ");
        jPanel16.add(indisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 170, 40));

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 190, 80));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        incpu.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        incpu.setText("AMD Ryzen 7 PRO - 6850U                 ");
        jPanel17.add(incpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 140, 40));

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 160, 80));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inssd.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        inssd.setText("Gaming Asus TUF Core i7 12700H          ");
        jPanel18.add(inssd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 150, 40));

        jPanel1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 170, 80));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vimg.setText("     none");
        vimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(vimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 40));

        inimg.setBackground(new java.awt.Color(255, 204, 153));
        inimg.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        inimg.setText("Chose");
        inimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inimgActionPerformed(evt);
            }
        });
        jPanel19.add(inimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, 60, 20));

        jPanel1.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 180, 80, 80));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inram.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        inram.setText("Gaming Asus TUF Core i7 12700H          ");
        jPanel20.add(inram, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 120, 40));

        jPanel1.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 140, 80));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        invga.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        invga.setText("Gaming Asus TUF Core i7 12700H          ");
        jPanel21.add(invga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 150, 40));

        jPanel1.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 170, 80));

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inprice.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        inprice.setText("Gaming Asus TUF Core i7 12700H          ");
        jPanel22.add(inprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 100, 40));

        jPanel1.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 180, 120, 80));

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inpriceS.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        inpriceS.setText("65.000.000");
        jPanel23.add(inpriceS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 40));

        jPanel1.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 180, 90, 80));

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inid.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        inid.setText("10");
        jPanel24.add(inid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 30, 40));

        jPanel1.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 180, 50, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CANCELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANCELMouseClicked
        try {
            new Manager(ManaName).setVisible(true);dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(editSP.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(editSP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CANCELMouseClicked

    private void incolorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incolorMouseClicked
        
        
    }//GEN-LAST:event_incolorMouseClicked
    private void DONEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DONEMouseClicked
        try {
            Connection conn=db.DBconnect.getConnection();
            String sql="select *from laptop";
            PreparedStatement ps=conn.prepareCall(sql);
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                if(rs.getString(1).contains(idName)){  
                    sql="delete from laptop where Name='"+idName+"';";
                    ps=conn.prepareCall(sql);
                    ps.execute();
                    sql = "INSERT INTO laptop " +
                        "VALUES ('"+inname.getText()+"', '"+incpu.getText()+"', '"+inram.getText()+"', '"
                                +inssd.getText()+"', '"+invga.getText()+"','"+indisplay.getText()+"','"+incolor.getSelectedItem().toString()
                            +"',"+inprice.getText()+","+inid.getText()+",'"+inpriceS.getText()+"','"+newlink+"')";
                    ps=conn.prepareCall(sql);
                    ps.execute();
                    break;
                }
            new Manager(ManaName).setVisible(true);
            dispose();
            }
            
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_DONEMouseClicked

    private void inimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inimgActionPerformed
        JFileChooser f=new JFileChooser("C:\\Users\\DUC\\Documents\\JAVA\\BanLapTop\\src\\com.icon");
        f.setDialogTitle("Chọn ảnh");
        f.showOpenDialog(null);
        File nf=f.getSelectedFile();
        newlink=nf.getAbsolutePath();
        if(newlink!=null){
            scaleImage(nf.getAbsolutePath(), vimg);
        }else{
            newlink=oldlink;
        }
    }//GEN-LAST:event_inimgActionPerformed

    public JButton getCANCEL() {
        return CANCEL;
    }

    public JButton getDONE() {
        return DONE;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new editSP("v", "v").setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(editSP.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(editSP.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CANCEL;
    private javax.swing.JButton DONE;
    private javax.swing.JPanel bottom;
    private javax.swing.JPanel color;
    private javax.swing.JLabel cpu;
    private javax.swing.JLabel display;
    private javax.swing.JLabel id;
    private javax.swing.JLabel img;
    private javax.swing.JComboBox<String> incolor;
    private javax.swing.JTextField incpu;
    private javax.swing.JTextField indisplay;
    private javax.swing.JTextField inid;
    private javax.swing.JButton inimg;
    private javax.swing.JTextField inname;
    private javax.swing.JTextField inprice;
    private javax.swing.JTextField inpriceS;
    private javax.swing.JTextField inram;
    private javax.swing.JTextField inssd;
    private javax.swing.JTextField invga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel price;
    private javax.swing.JLabel priceS;
    private javax.swing.JLabel ram;
    private javax.swing.JLabel ssd;
    private javax.swing.JLabel tensp;
    private javax.swing.JPanel vcolor;
    private javax.swing.JLabel vga;
    private javax.swing.JLabel vimg;
    // End of variables declaration//GEN-END:variables
}
