/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.main;

import db.DBconnect;
import java.awt.Color;
import java.sql.Connection;
import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author DUC
 */
public class introduce extends javax.swing.JFrame {
    private String Link;
    private String Name;
//    private String Cpu;
//    private String Ram;
//    private String Vga;
//    private String Ssd;
//    private String Display;
//    private String Color;
    private String Price;
    private int stt=1,soluong=1;
    private static Color black=Color.BLACK;
    private static Color white=Color.WHITE;
    private static Color gray=Color.GRAY;
    private static Color blue=Color.BLUE;
    /**
     * Creates new form introduce
     */
    public introduce() {        
        initComponents();
        scaleImage("C:\\Users\\DUC\\Documents\\JAVA\\BanLapTop\\src\\com.icon\\cart.jpg", carticon);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    public introduce(String File, String Name, String Cpu, String Ram, String Vga, String Ssd, String Display, String Color, String Price) {
        initComponents();
        this.Name=Name;
        this.Price=Price;
        this.Link=File;
        
        name.setText(Name+"");
        cpu.setText(Cpu);
        ram.setText(Ram);
        vga.setText(Vga);
        ssd.setText(Ssd);
        display.setText(Display);
        color.setText(Color);
        price.setText("Giá: "+Price);
        if(Color.contains("White")){
            color.setForeground(white);
        }else if(Color.contains("Black")){
            color.setForeground(black);
        }else if(Color.contains("Gray")){
            color.setForeground(gray);
        }else if(Color.contains("Blue")){
            color.setForeground(blue);
        }
        
        scaleImage(File, imglaptop);
        scaleImage("C:\\Users\\DUC\\Documents\\JAVA\\BanLapTop\\src\\com.icon\\cart.jpg", carticon);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
    }
    private void scaleImage(String location, JLabel label){
        ImageIcon icon = new ImageIcon(location);
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        label.setIcon(scaledIcon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imglaptop = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cpu = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ram = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ssd = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        vga = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        display = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        price = new javax.swing.JLabel();
        donebuton = new javax.swing.JButton();
        addtocart = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        carticon = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        color = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Information");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        imglaptop.setBackground(new java.awt.Color(153, 255, 255));
        imglaptop.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        imglaptop.setForeground(new java.awt.Color(153, 153, 255));
        imglaptop.setText("sdsssssssss");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(imglaptop, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(imglaptop, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 360));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        name.setText("Gaming Asus TUF Core i7 12700H          ");
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 460, 49));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("CPU :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 40, 30));

        cpu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cpu.setForeground(new java.awt.Color(51, 102, 255));
        cpu.setText("AMD Ryzen 7 PRO - 6850U                 ");
        jPanel2.add(cpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 260, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("RAM :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 30));

        ram.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ram.setForeground(new java.awt.Color(51, 102, 255));
        ram.setText("32GB DDR4-3200MHz                       ");
        jPanel2.add(ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 240, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Hard drive :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 80, 30));

        ssd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ssd.setForeground(new java.awt.Color(51, 102, 255));
        ssd.setText("SSD 256 GB PCIe NVMe M.2                ");
        jPanel2.add(ssd, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 270, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("VGA :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 60, 30));

        vga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vga.setForeground(new java.awt.Color(51, 102, 255));
        vga.setText("NVIDIA GeForce RTX 3050 Ti 4GB GDDR6    ");
        jPanel2.add(vga, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 300, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Display :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 80, 30));

        display.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        display.setForeground(new java.awt.Color(51, 102, 255));
        display.setText("15.6 inch, 2560 x 1440 , IPS, 165 Hz    ");
        jPanel2.add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 260, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 550, 10));

        price.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        price.setForeground(new java.awt.Color(255, 0, 0));
        price.setText("Giá: 56.000.000     Đ");
        jPanel2.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 230, 50));

        donebuton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        donebuton.setForeground(new java.awt.Color(255, 102, 0));
        donebuton.setText("DONE");
        donebuton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donebutonMouseClicked(evt);
            }
        });
        donebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donebutonActionPerformed(evt);
            }
        });
        jPanel2.add(donebuton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 70, 50));

        addtocart.setBackground(new java.awt.Color(255, 255, 255));
        addtocart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addtocart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocartMouseClicked(evt);
            }
        });
        addtocart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 102, 0));
        jLabel18.setText("Thêm vào giỏ");
        addtocart.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 6, 120, 40));

        carticon.setText("jLabel19");
        addtocart.add(carticon, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, 40, 40));

        jPanel2.add(addtocart, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 190, 50));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        color.setBackground(new java.awt.Color(255, 255, 255));
        color.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        color.setForeground(new java.awt.Color(51, 102, 255));
        color.setText("Black");
        jPanel3.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 70, 40));

        jLabel16.setBackground(new java.awt.Color(204, 204, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText(" Color :");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 550, 280));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, 60));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 660, 110, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void donebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donebutonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donebutonActionPerformed

    private void donebutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donebutonMouseClicked
        new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_donebutonMouseClicked

    private void addtocartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocartMouseClicked
        try {
            Connection conn=DBconnect.getConnection();
            String sql="select *from giohang";
            PreparedStatement ps=conn.prepareCall(sql);
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                if(rs.getString("Name").contains(this.Name)){
                    this.soluong=rs.getInt(4);
                    this.stt=rs.getInt(5);
                    sql="delete from giohang where stt="+this.stt+";";
                    ps=conn.prepareCall(sql);
                    ps.execute();
                    sql = "INSERT INTO giohang " +
                    "VALUES ('"+this.Name+"', '"+this.Price+"', '"+this.Link+"',"+(this.soluong+1)+", "+(this.stt)+")";
                    ps=conn.prepareCall(sql);
                    ps.execute();
                    stt=0;
                    break;
                }
                ++stt;
            }
            if(stt!=0){
                
                sql = "INSERT INTO giohang " +
                    "VALUES ('"+this.Name+"', '"+this.Price+"', '"+this.Link+"',"+(this.soluong)+", "+(this.stt)+")";
                ps=conn.prepareCall(sql);
                ps.execute();
            }
            new Home().setVisible(true);
            dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_addtocartMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(introduce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(introduce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(introduce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(introduce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new introduce().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addtocart;
    private javax.swing.JLabel carticon;
    private javax.swing.JLabel color;
    private javax.swing.JLabel cpu;
    private javax.swing.JLabel display;
    private javax.swing.JButton donebuton;
    private javax.swing.JLabel imglaptop;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel price;
    private javax.swing.JLabel ram;
    private javax.swing.JLabel ssd;
    private javax.swing.JLabel vga;
    // End of variables declaration//GEN-END:variables
}
